vich_uploader:
    db_driver: orm
    metadata:
        type: attributes

    mappings:
        carrousel_images:
            uri_prefix: NB-services-et-soin/current/public/images/carroussel
            upload_destination: '%kernel.project_dir%/public/images/carrousel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
