vich_uploader:
    db_driver: orm # or mongodb orm or phpcr
    metadata:
        type: attribute

    mappings:
        images:
            uri_prefix: /images/nbss
            upload_destination: '%kernel.project_dir%/public/images/nbss'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
